pip install -r requirements.txt

if command -v apt-get 2>/dev/null; then
    sudo apt update -y
    sudo apt-get install -y libmagic-dev
elif command -v brew 2>/dev/null; then
    brew install libmagic
else 
    printf "This project requires libmagic. Figure out how to install it, then hit [Enter] to continue."
    read
fi

printf "What is your Mailgun username? (It's an email address) "
read -r mailgun_user
printf "Enter the API key for your account at this prompt (look here if you don't know it: https://app.mailgun.com/app/account/security/api_keys)\n"
keyring set api.mailgun.com $mailgun_user

printf "Ready to overwrite environment.py? "
read
rm environment.py 2>/dev/null

printf "ENVIRONMENT = (probably: production) "
read -r environment

printf "EMAIL_RECIPIENT = (something like: Your Name <your@email.address>) "
read -r email_recipient
printf "EMAIL_SENDER = (something like: Your NewsBot <your-newsbot@your.newsbot.domain>) "
read -r email_sender
printf "EMAIL_SENDER_DOMAIN = (something like: your.newsbot.domain) "
read -r email_sender_domain

printf "# This document was generated by config.sh\n\n" >> environment.py
printf "ENVIRONMENT = '$environment'\n\n" >> environment.py
printf "EMAIL_RECIPIENT = '$email_recipient'\n" >> environment.py
printf "EMAIL_SENDER = '$email_sender'\n" >> environment.py
printf "EMAIL_SENDER_DOMAIN = '$email_sender_domain'\n\n" >> environment.py
printf "MAILGUN_API_USER = '$mailgun_user'\n" >> environment.py

printf "make sure this looks right:\n"
cat environment.py
